FROM docker.io/apache/airflow:3.0.0

# Update system and remove cache to reduce vulnerabilities
USER root
RUN apt-get update && apt-get upgrade -y && apt-get clean && rm -rf /var/lib/apt/lists/*

# Switch back to airflow user
USER airflow

# Customizations can be added here if needed
