version: '3.8'
services:
  airflow-webserver:
    image: docker.io/apache/airflow:3.0.0
    restart: always
    command: api-server
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: your_fernet_key
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: 8080
    volumes:
      - ../dags:/opt/airflow/dags
      - airflow-logs:/opt/airflow/logs
      - ../airflow-db:/opt/airflow  # <-- Add this line
    ports:
      - "8080:8080"

  nginx:
    image: docker.io/nginx:latest
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - airflow-webserver

volumes:
  airflow-logs:
    depends_on:
      - airflow-webserver

volumes:
  airflow-logs:
